### ISSUE TITLE
Without the The biometrics

### ISSUE THREAD

**Issue by justiniii** [ZackFreedman/Chromance#1]
Could someone mod this to make it do what it does randomly without the biometrics and be able to change settings with the wifi.

**Comment by jamiejcole** [comment]
Would love this!

**Comment by ZackFreedman** [comment]
The firmware has two fallback behaviors that kick in if five seconds pass between heartbeats! You can have it fire random rainbow ripples or simulate biometric behavior.

Unfortunately, I'm not a great Web coder... I'm not sure how to even write that!

**Comment by ztaylor54** [comment]
Planning on implementing an audio visualizer with this. Will submit a PR when I have it!

**Comment by justiniii** [comment]
> Planning on implementing an audio visualizer with this. Will submit a PR when I have it!

I would love this

**Comment by justiniii** [comment]
> The firmware has two fallback behaviors that kick in if five seconds pass between heartbeats! You can have it fire random rainbow ripples or simulate biometric behavior.
> 
> Unfortunately, I'm not a great Web coder... I'm not sure how to even write that!

Would it be possible to make it just random ripples without the hear sensors.

**Comment by ZackFreedman** [comment]
This is already implemented. Please read the readme.
