### ISSUE TITLE
RegularNode.f3d in Models is not the Regular node

### ISSUE THREAD

**Issue by n3rdz** [ZackFreedman/Chromance#4]
The RegularNode.f3d you uploaded  under "Models" is not the Regular Node but the Topleft Node.

![2021-05-27 01_18_54-Autodesk Fusion 360 (Persönlich - nicht zur kommerziellen Nutzung)](https://user-images.githubusercontent.com/10661438/119743154-87054a80-be89-11eb-892c-e6cd011823ca.png)

**Comment by ZackFreedman** [comment]
I made a boo-boo when I got a pull request - I closed it instead of accepting it and merging it. Correct model should now be up.
