### ISSUE TITLE
What is the total size in dimentions?

### ISSUE THREAD

**Issue by nobels** [ZackFreedman/Chromance#6]
Hello,

I wonder if you just can share the size in dimentions :-)

Before I like to build this, i would like to know if this fits on my wall. (or ceiling)

Thanks

**Comment by aaronse** [comment]
Guessing ~1.2m wide by ~1m high for current checked in code and build instructions, with hex arrangement of 23cm lengths.  However, people can customize the graph node-edge definitions in mapping.h to other dimensions and layouts to fit their chromance desires.

Would be interesting to see alternative mappings and layouts people end up building.

**Comment by nobels** [comment]
That is the plan ... but i would like to start with yours ;-)
Thanks for the feedback.
